### ISSUE TITLE
Stack Buffer Overflow in grass::FileTransfer::transferWorker()

### ISSUE THREAD

**Issue by hazimeh** [matrizzo/cs412-project#3]
A vulnerability exists in `grass::FileTransfer::transferWorker()`, at _filetransfer.cpp:81_, where an OOB write is performed on a fixed-size stack buffer.

The allocated buffer of 4096 bytes is the destination of a socket read operation of 4200 bytes. This operation is performed when a put command is issued. Upon disassembly of the server binary, it becomes evident that, in fact, the last 4 bytes of a 4124-byte file will overwrite the return address in the stack frame of the current function.

For the sake of this demonstration, the buffer will be filled with 1031 4-byte words (for a total of 4124 bytes), each word containing the address of the `hijack_flow()` method: _0x5656e5a1_. The “in” script, in the attached PoC, contains a login sequence followed by a put command for the file, and a new-line character.

[sploit_2.zip](https://github.com/matrizzo/cs412-project/files/3171979/sploit_2.zip)

**Comment by AymericGenet** [comment]
If I may add a comment here, the command `put <file> <size>` does not properly consider the provided size (server and client). Hence, using the provided exploit files, since the size is less than 4200, a `put file 1` command would still send the whole file and execute the exploit, even though the size is greater than 1 byte.

If the size was greater than 4200, only the first 4200 bytes would have been written in the file, leaving the difference inside the socket buffer.

I would fix this by sending (resp. receiving) only the first `<size>` bytes of the file content, as the code is supposedly intended to do by examining the receiving end:

**Client side**
- In the `grass::ClientManager` class, add a way to include the size in the `_files_to_send` queue (by either including the size in the string, or using a tuple).
- In `grass::ClientManager::sendFile`, pass the now retrievable file size as a parameter to the `grass::ClientManager::sendFileWorker` function.
- In `grass::ClientManager::sendFileWorker`, use the file size parameter instead of the `stat.st_size` (but still compare the two quantities in order to pad the difference with zeroes or throw an error if the parameter exceeds `stat.st_size`? This can also be prevented earlier to prevent invalid file sizes).

**Server side**
- In `grass::FileTransfer::transferWorker`, accumulate the `read_bytes` and check that the accumulation does not exceed the given `file_size` inside of the while loop condition (instead of this ugly `break`).

**Comment by RomainMendez** [comment]
We are reoppening this issue because @AymericGenet 's comment is correct, but the vulnerability is fixed.
